# Generated by Django 4.0.4 on 2022-05-03 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_request',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 0, 0)),
        ),
    ]
